// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: factorial.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpreadType int32

const (
	SpreadType_None   SpreadType = 0
	SpreadType_Spread SpreadType = 1
	SpreadType_Points SpreadType = 2
)

// Enum value maps for SpreadType.
var (
	SpreadType_name = map[int32]string{
		0: "None",
		1: "Spread",
		2: "Points",
	}
	SpreadType_value = map[string]int32{
		"None":   0,
		"Spread": 1,
		"Points": 2,
	}
)

func (x SpreadType) Enum() *SpreadType {
	p := new(SpreadType)
	*p = x
	return p
}

func (x SpreadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpreadType) Descriptor() protoreflect.EnumDescriptor {
	return file_factorial_proto_enumTypes[0].Descriptor()
}

func (SpreadType) Type() protoreflect.EnumType {
	return &file_factorial_proto_enumTypes[0]
}

func (x SpreadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpreadType.Descriptor instead.
func (SpreadType) EnumDescriptor() ([]byte, []int) {
	return file_factorial_proto_rawDescGZIP(), []int{0}
}

// CalculateRequest is request with numbers for which should be calculating factorial
type CalculateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers   []int64     `protobuf:"varint,1,rep,packed,name=Numbers,proto3" json:"Numbers,omitempty"` // Value into Numbers shouldn't be negative
	MinSpread *SpreadData `protobuf:"bytes,20,opt,name=min_spread,json=minSpread,proto3" json:"min_spread,omitempty"`
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factorial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_factorial_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *CalculateRequest) GetMinSpread() *SpreadData {
	if x != nil {
		return x.MinSpread
	}
	return nil
}

// CalculateResult is response with resulted data
type CalculateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputNumber     int64  `protobuf:"varint,1,opt,name=InputNumber,proto3" json:"InputNumber,omitempty"`        // InputNumber is number which added by CalculateRequest
	FactorialResult string `protobuf:"bytes,2,opt,name=FactorialResult,proto3" json:"FactorialResult,omitempty"` // Result for input nuber converted to string
}

func (x *CalculateResult) Reset() {
	*x = CalculateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResult) ProtoMessage() {}

func (x *CalculateResult) ProtoReflect() protoreflect.Message {
	mi := &file_factorial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResult.ProtoReflect.Descriptor instead.
func (*CalculateResult) Descriptor() ([]byte, []int) {
	return file_factorial_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResult) GetInputNumber() int64 {
	if x != nil {
		return x.InputNumber
	}
	return 0
}

func (x *CalculateResult) GetFactorialResult() string {
	if x != nil {
		return x.FactorialResult
	}
	return ""
}

type SpreadData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SpreadType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.SpreadType" json:"type,omitempty"`
	Data float64    `protobuf:"fixed64,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SpreadData) Reset() {
	*x = SpreadData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorial_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpreadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpreadData) ProtoMessage() {}

func (x *SpreadData) ProtoReflect() protoreflect.Message {
	mi := &file_factorial_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpreadData.ProtoReflect.Descriptor instead.
func (*SpreadData) Descriptor() ([]byte, []int) {
	return file_factorial_proto_rawDescGZIP(), []int{2}
}

func (x *SpreadData) GetType() SpreadType {
	if x != nil {
		return x.Type
	}
	return SpreadType_None
}

func (x *SpreadData) GetData() float64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_factorial_proto protoreflect.FileDescriptor

var file_factorial_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x70,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x6d,
	0x69, 0x6e, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x22, 0x5d, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x0f, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x47, 0x0a, 0x0a, 0x53, 0x70, 0x72, 0x65, 0x61,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x72, 0x65,
	0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x2a, 0x2e, 0x0a, 0x0a, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x70, 0x72, 0x65,
	0x61, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x10, 0x02,
	0x32, 0x4b, 0x0a, 0x09, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x3e, 0x0a,
	0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_factorial_proto_rawDescOnce sync.Once
	file_factorial_proto_rawDescData = file_factorial_proto_rawDesc
)

func file_factorial_proto_rawDescGZIP() []byte {
	file_factorial_proto_rawDescOnce.Do(func() {
		file_factorial_proto_rawDescData = protoimpl.X.CompressGZIP(file_factorial_proto_rawDescData)
	})
	return file_factorial_proto_rawDescData
}

var file_factorial_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_factorial_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_factorial_proto_goTypes = []interface{}{
	(SpreadType)(0),          // 0: proto.SpreadType
	(*CalculateRequest)(nil), // 1: proto.CalculateRequest
	(*CalculateResult)(nil),  // 2: proto.CalculateResult
	(*SpreadData)(nil),       // 3: proto.SpreadData
}
var file_factorial_proto_depIdxs = []int32{
	3, // 0: proto.CalculateRequest.min_spread:type_name -> proto.SpreadData
	0, // 1: proto.SpreadData.type:type_name -> proto.SpreadType
	1, // 2: proto.Factorial.Calculate:input_type -> proto.CalculateRequest
	2, // 3: proto.Factorial.Calculate:output_type -> proto.CalculateResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_factorial_proto_init() }
func file_factorial_proto_init() {
	if File_factorial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_factorial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factorial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factorial_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpreadData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_factorial_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factorial_proto_goTypes,
		DependencyIndexes: file_factorial_proto_depIdxs,
		EnumInfos:         file_factorial_proto_enumTypes,
		MessageInfos:      file_factorial_proto_msgTypes,
	}.Build()
	File_factorial_proto = out.File
	file_factorial_proto_rawDesc = nil
	file_factorial_proto_goTypes = nil
	file_factorial_proto_depIdxs = nil
}
